### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by krzysztofantczak** [sanbornm/go-selfupdate#1]
Hi,

Does this module still work? I'm kind of new to GO but no idea if i'm doing something wrong or module doesn't work anymore, i'm using your exact code from readme and i'm getting:

```
$ go run test.go
# github.com/sanbornm/go-selfupdate/selfupdate
../../../github.com/sanbornm/go-selfupdate/selfupdate/selfupdate.go:79: undefined: update.SanityCheck
../../../github.com/sanbornm/go-selfupdate/selfupdate/selfupdate.go:144: undefined: update.FromStream
```

**Comment by thomasf** [comment]
Why are you not using the latest version of go-update?

**Comment by thomasf** [comment]
Seems like someone already migrated the version (?) 

The commit is a bit noisy to read because it implements the change and gofmt is run a well.

https://github.com/canerdogan/go-selfupdate/commit/c2f128aaaf59c3e16445f5a754734e9e1ee5e0e5

**Comment by sanbornm** [comment]
> Why are you not using the latest version of go-update?

No reason, I just pulled the update from canerdogan@c2f128a

Thanks for reporting
