### ISSUE TITLE
Need Some Examples to understand self update

### ISSUE THREAD

**Issue by shageeth** [sanbornm/go-selfupdate#21]

**Comment by frostarun** [comment]
yes that would be helpful , Many people are confused with provided example . @sanbornm

**Comment by joeblew99** [comment]
Hey all 

You can use godoc to find other project that import this code.
There is one at least :) Hope this helps


https://godoc.org/github.com/sanbornm/go-selfupdate/selfupdate?importers

**Comment by deinspanjer** [comment]
we have an example now so this could probably be closed.

**Comment by joeblew99** [comment]
thanks nice !!
