### ISSUE TITLE
how to self-update mac apps with .app structure

### ISSUE THREAD

**Issue by rsaccon** [sanbornm/go-selfupdate#7]
My go app is a CGO compiled Mac OS X application with a typical <APPNAME>.app folder, which contains the binary, resource files, frameworks and more. Can I use go-selfupdate for that ?

**Comment by sanbornm** [comment]
Hi Roberto

I am honestly not sure. Go-selfupdate updates the binary it was called from
in place so it should work in any folder structure.

Can you please try it and let us know?

On Saturday, April 4, 2015, Roberto Saccon <notifications@github.com> wrote:

> My go app is a CGO compiled Mac OS X application with a typical .app
> folder, which contains the binary, resource files, frameworks and more. Can
> I use go-selfupdate for that ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sanbornm/go-selfupdate/issues/7>.
>


-- 
Mark Sanborn
707-726-2676

**Comment by coreybutler** [comment]
I haven't used go-selfupdate yet (I'm researching which tool I want to use).... but @rsaccon's issue sounds like one better suited for https://github.com/Squirrel/Squirrel.Mac. That's the platform Electron uses to do `.app` updates.
